version: "2"


services:
  mariadb:
    container_name: "${PROJECT_NAME}_mariadb"
    image: mariadb:latest
    command: --max_allowed_packet=67108864
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - mariadb:/var/lib/mysql
#      - /path/to/mariadb/data/on/host:/var/lib/mysql # I want to manage volumes manually.
      - ./mariadb/dump:/home/mariadb/dump
      - ./mariadb/init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
#    ports:
#      - "3306:3306"

  matomo:
    container_name: "${PROJECT_NAME}_matomo"
    image: matomo:fpm
    links:
      - mariadb
    volumes:
      - ./matomo/config:/var/www/html/config
      - ./matomo/logs:/var/www/html/logs

  nginx:
    container_name: "${PROJECT_NAME}_nginx"
    build: ./nginx
    #command: "/bin/sh -c 'while :; do certbot renew; nginx -s reload; sleep 24h & wait $${!}; done & nginx -g \"daemon off;\"'"
    environment:
      EMAIL: $PROJECT_EMAIL
      DOMAINS: $PROJECT_DOMAINS
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - nginx:/etc/letsencrypt
      - nginx:/var/www/certbot
    links:
      - matomo
    volumes_from:
      - matomo
    ports:
      - "80:80"
      - "443:443"

  redis:
    container_name: "${PROJECT_NAME}_redis"
    image: redis:latest
#    ports:
#      - "6379:6379"


volumes:
  mariadb:
    driver: local
  nginx:
    driver: local

