version: "3"

db:
  container_name: "${PROJECT_NAME}_mariadb"
  image: mariadb:latest
  stop_grace_period: 30s
  environment:
    MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    MYSQL_DATABASE: $MYSQL_DATABASE
    MYSQL_USER: $MYSQL_USER
    MYSQL_PASSWORD: $MYSQL_PASSWORD
  volumes:
    - mariadb:/var/lib/mysql
#    - /path/to/mariadb/data/on/host:/var/lib/mysql # I want to manage volumes manually.
    - ./mariadb/dump:/home/mariadb/dump
    - ./mariadb/init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
#  ports:
#    - "3306:3306"

matomo:
  container_name: "${PROJECT_NAME}_matomo"
  image: matomo:fpm
  links:
    - db
  volumes:
    - ./config:/var/www/html/config
    - ./logs:/var/www/html/logs
  env_file:
    - ./matomo.env

nginx:
  container_name: "${PROJECT_NAME}_nginx"
  image: nginx:latest
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  links:
    - matomo
  volumes_from:
    - matomo
#  ports:
#    - "80:80"
#    - "443:443"

redis:
  container_name: "${PROJECT_NAME}_redis"
  image: redis:latest
#  ports:
#    - "6379:6379"